services:
  - type: web
    name: student-attendance-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DATABASE_URL
        fromDatabase:
          name: student_attendance_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    plan: free
